name: Generate Diagrams from LinkML

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      - 'docs/*.linkml.yaml'
      - '.github/workflows/generate-diagrams.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-and-render:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps (PyYAML)
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml

      - name: Create output dir
        run: |
          mkdir -p docs/diagrams/generated

      - name: Convert LinkML -> PlantUML (.puml)
        # Inline Python converter: reads LinkML YAML and writes a simple PUML per class
        run: |
          python - <<'PY'
          import sys, yaml, pathlib
          src = pathlib.Path("docs/flexibility_products.linkml.yaml")
          if not src.exists():
              print("Source LinkML not found:", src)
              sys.exit(0)
          data = yaml.safe_load(src.read_text())
          classes = data.get("classes", {}) or {}
          slots = data.get("slots", {}) or {}

          outp = pathlib.Path("docs/diagrams/generated/flexibility_products_auto.puml")
          lines = ["@startuml", "title Auto-generated: flexibility_products.linkml.yaml", ""]
          # write classes and attributes
          for cname, cdef in classes.items():
              lines.append(f"class {cname} {{")
              for s in (cdef.get("slots") or []):
                  # slot can be a dict or name
                  sname = s if isinstance(s, str) else s.get("name", "<slot>")
                  sdef = slots.get(sname, {}) or {}
                  r = sdef.get("range", "string")
                  mult = sdef.get("multivalued", False)
                  ident = sdef.get("identifier", False)
                  prefix = "+" if ident else "-"
                  suffix = "[]" if mult else ""
                  lines.append(f"  {prefix} {sname} : {r}{suffix}")
              lines.append("}")
              lines.append("")
          # infer simple relationships from slots with class ranges
          for sname, sdef in slots.items():
              r = sdef.get("range")
              if isinstance(r, str) and r in classes:
                  # find classes that use this slot
                  for cname, cdef in classes.items():
                      if sname in (cdef.get("slots") or []):
                          mult = sdef.get("multivalued", False)
                          lines.append(f'{cname} "1" --> {"\"0..*\"" if mult else "\"1\""} {r} : {sname}')
          lines.append("")
          lines.append("@enduml")
          outp.parent.mkdir(parents=True, exist_ok=True)
          outp.write_text("\n".join(lines), encoding="utf-8")
          print("Wrote", outp)
          PY

      - name: Show generated PUML files
        run: |
          find docs/diagrams -name '*.puml' -print || true
          sed -n '1,200p' docs/diagrams/generated/flexibility_products_auto.puml || true

      - name: Install Graphviz and Java (for PlantUML rendering)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends openjdk-11-jre-headless graphviz curl unzip
          sudo rm -rf /var/lib/apt/lists/*

      - name: Download plantuml.jar
        run: |
          mkdir -p /opt/plantuml
          curl -sL -o /opt/plantuml/plantuml.jar https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar
          echo "Downloaded plantuml.jar" && java -jar /opt/plantuml/plantuml.jar -version || true

      - name: Render PUML -> SVG and PNG
        run: |
          # render all .puml under docs/diagrams
          find docs/diagrams -type f -name '*.puml' | while read -r f; do
            echo "Rendering $f"
            java -jar /opt/plantuml/plantuml.jar -tsvg "$f" || true
            java -jar /opt/plantuml/plantuml.jar -tpng "$f" || true
          done

      - name: Show generated images
        run: |
          find docs/diagrams -type f \( -name '*.svg' -o -name '*.png' \) -print || true

      - name: Commit and push generated diagrams (if any)
        env:
          GIT_AUTHOR_NAME: "github-actions[bot]"
          GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"
        run: |
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          git add docs/diagrams || true
          if ! git diff --cached --quiet; then
            git commit -m "ci: auto-generate diagrams from LinkML [skip ci]" || true
            git push origin HEAD || true
            echo "Committed generated diagrams"
          else
            echo "No changes to commit"
          fi