openapi: 3.0.3
info:
  title: Energy Regulation Volume (Notification) API
  version: "1.0.0"
  description: |
    Minimal OAS 3.0 model for the "EnergyRegulationVolumeNotification" business service.
    Field definitions and multiplicities are taken from the Business Service - Uitwisselen
    afgeroepen regelbaar vermogen (EDSN / MFF BAS) specification. :contentReference[oaicite:1]{index=1}
servers:
  - url: https://api.example-dso.nl/v1
    description: Example DSO API (replace per deployment)

security:
  - ApiKeyAuth: []

paths:
  /energy-regulation/notifications:
    post:
      summary: Submit Energy Regulation Volume Notification (provider -> consumer/MMC-Hub)
      description: |
        Accepts an EnergyRegulationVolumeNotification payload. This maps to the
        XML message *EnergyRegulationVolumeNotification* (see Business Service sections 4 & 7). :contentReference[oaicite:2]{index=2}
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnergyRegulationVolumeNotification'
      responses:
        "201":
          description: Notification accepted (created)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationReceipt'
        "400":
          description: Validation error (see receiver validation rules in spec). :contentReference[oaicite:3]{index=3}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /energy-regulation/acknowledgements:
    post:
      summary: Submit Acknowledgement / Response to a Notification (consumer -> provider/MMC-Hub)
      description: |
        Accepts acknowledgement (confirmation or rejection). This maps to the
        *EnergyRegulationVolumeAcknowledgement* message described in the Business Service. :contentReference[oaicite:4]{index=4}
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnergyRegulationVolumeAcknowledgement'
      responses:
        "200":
          description: Acknowledgement processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AckReceipt'
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

  schemas:

    # Top-level notification message (fields & multiplicities per PDF sections 4.1 & 7.2)
    EnergyRegulationVolumeNotification:
      type: object
      required:
        - mRID
        - startDateTime
        - endDateTime
        - marketProductType
        - product
        - measureUnit
        - accountingPoint
        - marketDocument
        - marketParticipant
        - marketRole
        - processType
        - series
      properties:
        mRID:
          type: string
          description: Unique identifier (UUID) for the message (MarketDocument.mRID). See PDF §4.1/7.2. :contentReference[oaicite:5]{index=5}
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        startDateTime:
          type: string
          format: date-time
          description: ISO 8601 UTC start date/time (YYYY-MM-DDThh:mm:ssZ). See PDF §1.3 and §4.1. :contentReference[oaicite:6]{index=6}
          example: "2026-10-28T16:00:00Z"
        endDateTime:
          type: string
          format: date-time
          description: ISO 8601 UTC end date/time. Must be same calendar day and multiple of 15 minutes per PDF. :contentReference[oaicite:7]{index=7}
          example: "2026-10-28T16:30:00Z"
        marketProductType:
          type: string
          description: Regulation direction (CIM code list). Allowed values per document: RU (Regulation Up) or RD (Regulation Down). :contentReference[oaicite:8]{index=8}
          enum: ["RU","RD"]
          example: "RU"
        product:
          $ref: '#/components/schemas/Product'
        measureUnit:
          type: string
          description: Unit code (ebIX list). Document shows MAW (Megawatt) for electricity. :contentReference[oaicite:9]{index=9}
          example: "MAW"
        accountingPoint:
          $ref: '#/components/schemas/AccountingPoint'
        marketDocument:
          $ref: '#/components/schemas/MarketDocument'
        marketParticipant:
          $ref: '#/components/schemas/MarketParticipant'
        marketRole:
          type: string
          description: EbIX market role (e.g., DDK for Balance Responsible Party). See PDF §7.2. :contentReference[oaicite:10]{index=10}
          example: "DDK"
        processType:
          type: string
          description: ENTSO-E process type. PDF lists A41 = Redispatch for this service. :contentReference[oaicite:11]{index=11}
          example: "A41"
        series:
          type: object
          required:
            - mRID
            - product
            - resolution
            - points
          properties:
            mRID:
              type: string
              description: Series identifier (UUID)
              example: "8d3f8e6c-6b1a-4d8b-9d2f-2a4bddf1a6b7"
            product:
              $ref: '#/components/schemas/Product'
            resolution:
              type: string
              description: ISO 8601 duration for step resolution. PDF shows PT15M for 15-minute ISP. :contentReference[oaicite:12]{index=12}
              example: "PT15M"
            points:
              type: array
              minItems: 1
              items:
                $ref: '#/components/schemas/Point'
          description: Time series for the notification (one series per message per the spec). :contentReference[oaicite:13]{index=13}
        notes:
          type: string
          description: Free text notes / additional fields (optional)

    Product:
      type: object
      required: [identification]
      properties:
        identification:
          type: string
          description: Product identification (ebIX code). PDF example: 8716867000030 (active electricity). :contentReference[oaicite:14]{index=14}
          example: "8716867000030"

    AccountingPoint:
      type: object
      required: [mRID]
      properties:
        mRID:
          type: string
          description: EAN18 accounting point identifier (allocation point). See PDF §7.2. :contentReference[oaicite:15]{index=15}
          example: "871234500000000001"

    MarketDocument:
      type: object
      required: [mRID, createdDateTime]
      properties:
        mRID:
          type: string
          description: Document identifier (UUID)
          example: "e7d9b3f6-2c8f-4e2f-a1a5-123456789abc"
        createdDateTime:
          type: string
          format: date-time
          example: "2026-10-28T15:45:00Z"

    MarketParticipant:
      type: object
      required: [mRID]
      properties:
        mRID:
          type: string
          description: EAN13 market participant identifier (GLN/EAN13). See PDF §7.2. :contentReference[oaicite:16]{index=16}
          example: "1234567890123"

    Point:
      type: object
      required: [position, quantity]
      properties:
        position:
          type: integer
          description: Sequential position value (1..n) in the time series. See PDF §7.2. :contentReference[oaicite:17]{index=17}
          example: 1
        quantity:
          type: number
          format: decimal
          description: Decimal volume (principal quantity). PDF requires **3** decimal places. Represent as number with multipleOf 0.001. :contentReference[oaicite:18]{index=18}
          multipleOf: 0.001
          example: 1.234

    # Acknowledgement / Response schema (per section 4.2 & 7.3)
    EnergyRegulationVolumeAcknowledgement:
      type: object
      required:
        - mRID
        - relatedNotificationMRID
        - createdDateTime
        - code
      properties:
        mRID:
          type: string
          description: Unique identifier (UUID) for the acknowledgement document. See PDF §4.2/7.3. :contentReference[oaicite:19]{index=19}
          example: "9a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"
        relatedNotificationMRID:
          type: string
          description: mRID of the notification being acknowledged (optional if message compromised — see note in PDF). :contentReference[oaicite:20]{index=20}
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        createdDateTime:
          type: string
          format: date-time
          example: "2026-10-28T16:02:00Z"
        code:
          type: string
          description: Acknowledgement code. Document: "000" for confirm; rejection codes per sections 3.3/3.4. :contentReference[oaicite:21]{index=21}
          example: "000"
        reason:
          type: object
          properties:
            code:
              type: string
              description: Reason code for rejection (see validation lists in PDF §§3.3–3.4)
              example: "BRP950"
            text:
              type: string
              description: Optional textual explanation
              example: "Invalid time period: start after end"

    NotificationReceipt:
      type: object
      properties:
        mRID:
          type: string
          description: The assigned identifier for the received notification (echoed)
        receivedAt:
          type: string
          format: date-time

    AckReceipt:
      type: object
      properties:
        mRID:
          type: string
        processedAt:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

  examples:
    NotificationExample:
      value:
        mRID: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        startDateTime: "2026-10-28T16:00:00Z"
        endDateTime: "2026-10-28T16:30:00Z"
        marketProductType: "RU"
        product:
          identification: "8716867000030"
        measureUnit: "MAW"
        accountingPoint:
          mRID: "871234500000000001"
        marketDocument:
          mRID: "e7d9b3f6-2c8f-4e2f-a1a5-123456789abc"
          createdDateTime: "2026-10-28T15:45:00Z"
        marketParticipant:
          mRID: "1234567890123"
        marketRole: "DDK"
        processType: "A41"
        series:
          mRID: "8d3f8e6c-6b1a-4d8b-9d2f-2a4bddf1a6b7"
          product:
            identification: "8716867000030"
          resolution: "PT15M"
          points:
            - position: 1
              quantity: 0.500
            - position: 2
              quantity: 0.500
